---
version: '2.3'
services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    volumes:
      - /mnt/configs/komga:/config
      - /mnt/media/bds:/books
      - /etc/timezone:/etc/timezone
    ports:
      - 8081:8080
    user: '1000:1000'
    restart: unless-stopped
    