---
version: '2.3'
services:

  emby:
    image: emby/embyserver:latest
    container_name: embyserver
    # runtime: nvidia # Expose NVIDIA GPUs
    # devices:
    #   - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    #   - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=${UID} # The UID to run emby as (default: 2)
      - GID=${GID} # The GID to run emby as (default 2)
    volumes:
      - /mnt/configs/emby:/config # Configuration directory      
      - lacie-media:/mnt/data # Media directory
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    restart: unless-stopped

volumes:
  lacie-media:
    driver: local
    opt:
      - type=cifs
      - device=${SMB_MEDIA_PATH_TO_SHARE}
      - uid=${UID},gid=${GID},credentials=${SMB_CREDS_FILE}
