---
version: '2.4'
services:

  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    ports:
        - 80:80
    volumes:
        - /mnt/configs/organizr:/config # Configuration directory
    environment:
        - fpm=true #true or false | using true will provide better performance
        - branch=v2-master #v2-master or #v2-develop
        - PUID=${UID}
        - PGID=${GID}
        - TZ=${TZ}

  emby:
    image: emby/embyserver:latest
    container_name: embyserver
    # runtime: nvidia # Expose NVIDIA GPUs
    # devices:
    #   - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    #   - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=${UID} # The UID to run emby as (default: 2)
      - GID=${GID} # The GID to run emby as (default 2)
    volumes:
      - /mnt/configs/emby:/config # Configuration directory
      # - emby-config:/config
      - lacie-media:/mnt/data # Media directory
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    restart: unless-stopped

  embystat:
    image: ghcr.io/linuxserver/embystat:latest
    container_name: embystat
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /mnt/configs/embystat:/config # Configuration directory
    ports:
      - 6555:6555
    restart: unless-stopped

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /mnt/configs/lidarr:/config # Configuration directory
      # - /path/to/music:/music
      - lacie-media:/mnt/media
      - /mnt/Downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
  
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - /mnt/configs/radarr:/config # Configuration directory
      # - /mnt/media/video/movies:/movies
      - lacie-media:/mnt/media
      - /mnt/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - /mnt/configs/sonarr:/config # Configuration directory
      # - /mnt/media/video/tv:/tv
      - lacie-media:/mnt/media
      - /mnt/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    ports:
      - 8080:8080
      - 9191:9090
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /mnt/configs/sabnzbd:/config
      - /mnt/Downloads:/downloads
      - /mnt/Downloads/sabnzbd-incomplete:/incomplete-downloads

# volumes:
#   lacie-media:
#     driver: local
#     driver_opts:
#       type: "cifs"
#       device: "${SMB_MEDIA_PATH_TO_SHARE}"
#       o: uid=${UID},gid=${GID},credentials=${SMB_CREDS_FILE}
